### PR TITLE
Make names case senstive as per directory name

### PR DESCRIPTION
**Pull request by allgandalf**

### CODE REVIEW

**Comment by allgandalf** [comment]
Can you please merge this PR @mdietze @Aariq :)

Please refer to the issue PecanProject/pecan#3210

**Review by mdietze — COMMENTED** [review]
I'm confused by this PR. Why do you want to change the package names in this file to be different from what the package names actually are in the build? This change clearly doesn't change the actual underlying package names.

**Comment by allgandalf** [comment]
I want the names in the makefile to be the same with the package names on the R universe, we are trying to install packages from Runiverse in order to avoid hitting the Github API rate limit, 

Now to do so, we got to install the packages from Runiverse using the makefile. So when i tried to run the script, it gave me error for the `db` package:

```bash
install base/db
  Installing package into ‘/usr/local/lib/R/site-library’
  (as ‘lib’ is unspecified)
  Warning messages:
  1: package ‘PEcAn.db’ is not available for this version of R
  ```
  
  This is because the name on R universe is PEcAn.DB and not PEcAn.db

**Comment by allgandalf** [comment]
> This change clearly doesn't change the actual underlying package names.

Where should the changes be made in order to change the package names of build on Runiverse?

https://pecanproject.r-universe.dev/builds

**Comment by mdietze** [comment]
The issue isn't that the package name on RUniverse are wrong. Those names are the correct names of those packages, see for example:
https://github.com/PecanProject/pecan/blob/ce327b92bf14498fa32fcf4ef500a7a5db5c9c6c/base/db/DESCRIPTION#L1

The error is occurring in whatever bit of code is trying to install PEcAn.db as there's no such package

**Comment by allgandalf** [comment]
We have makefile where we have defined the names of each packages and from there automated script is run to install all packages, see:

 https://github.com/PecanProject/pecan/blob/ce327b92bf14498fa32fcf4ef500a7a5db5c9c6c/Makefile#L3-L11
 
 The script is:
 
 ```R
install_R_pkg = ./scripts/time.sh "install ${1}" Rscript \
	-e ${SETROPTIONS} \
	-e "install.packages('PEcAn.$(notdir $(1))', repos = c('https://pecanproject.r-universe.dev', 'https://cloud.r-project.org'))"
```

So what would you suggest as a workaround over here?

Should i create different target names in the makefile according to the names on Runiverse? or do you see any other scope?

**Comment by Aariq** [comment]
I suspect this will break things.  The package names on r-universe should be whatever is in DESCRIPTION.

**Comment by mdietze** [comment]
So the problem here is that there's a false assumption in the Makefile, namely that 
```
install.packages('PEcAn.$(notdir $(1))'
```
is going to correctly predict the package name (i.e. the assumption that all PEcAn packages are named PEcAn.<dirname> is false). I think by far the simplest solution is to have a table that maps the directory name to the package name. Renaming the folders to match the package names could almost work, but won't handle cases where the package name doesn't have dots [indeed, there's a separate discussion about getting rid of those dot]). Renaming the underlying packages would be an enormous task, as you'd have to fix ever single time a function is called across the entirety of PEcAn, and this would also get wrong the cases where the package names don't include dots. Putting the dots back into PEcAnAssimSequential is categorically not an option because of C compliler issues in NIMBLE.

**Comment by Aariq** [comment]
Can't you just `install.packages("PEcAn.all")`?  That should install all the dependencies automatically.

**Pull request closed without merging**
